- getmailcore/_retrieverbases.py
Hey, thanks for this, I depend on getmail for my personal email, and am really thankful that you have done this python 3 work.
I noticed that sometimes decoding fails, and that trying with latin-1 allows the getmail to continue. Not sure if this is the best way to solve this problem, but works on my server.
> try with latin-1 on decode failure

- getmailcore/_retrieverbases.py
One more error I experienced with IDLE connections (I put this in a different PR because #15 ended up being about fixing capabilities in general, hope that's fine with you):
Terminating getmail6 when running persistent connection with IDLE would generate a type error when sending the 'DONE' because the underlying socket will expect a bytes-like object:
```
File "/usr/lib/python3.8/site-packages/getmailcore/_retrieverbases.py", line 1730, in go_idle
self.conn.send('DONE\r\n')
File "/usr/lib/python3.8/imaplib.py", line 323, in send
self.sock.sendall(data)
File "/usr/lib/python3.8/ssl.py", line 1201, in sendall
with memoryview(data) as view, view.cast("B") as byte_view:
TypeError: memoryview: a bytes-like object is required, not 'str'
```
> fix TypeError when trying to close IDLE connection

- MANIFEST.in
- setup.py
Building fails since commit 55564e94, which removed the TODO file. This
commit fixes this by simply  deleting references to this file from both
`MANIFEST.in` and `setup.py`.
> remove references to missing TODO file

- getmailcore/destinations.py
Mboxrd delivery agent opens the mbox file in byte mode, but os.linesep was concatenated to the argument of f.write() without .encode()
> Fix #20 (and a typo)

- setup.py
```
$ python3 setup.py build
/usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'install_requires'
warnings.warn(msg)
```
> Remove empty Unknown distribution option: 'install_requires'

- README
E.g., Debian (sid) explicitly does not provide "python"!
> Try "python2" or "python3" if there is no "python"

- docs/documentation.html
The user might not be online, hence cannot contact python.org to simply figure out the proper directory levels needed in PYTHONPATH.
> Give PYTHONPATH example

- getmailcore/_retrieverbases.py
Quote from Python docs:
> When an exception has been assigned using as target, it is cleared at
> the end of the except clause.
> fix UnboundLocalError when socket.error inside POP3_SSL_EXTENDED

- getmailcore/_retrieverbases.py
- getmailcore/imap_utf7.py
Support python 3.9 with new codec name comparisons (uses underscore instead of dash) and the new timeout argument to open.
Note as specified in the commit, the timeout argument is **not** actually handed due to the monkeypatch not supporting it.  It is just saved and ignored so that the code runs.
> Python 3.9 support -- codec name and timeout argument

- getmailcore/_retrieverbases.py
```
/usr/lib/python3.8/site-packages/getmailcore/_retrieverbases.py:1567: DeprecationWarning: invalid escape sequence \d
b'X-GM-THRID (?P<THRID>\d+) X-GM-MSGID (?P<MSGID>\d+)'
/usr/lib/python3.8/site-packages/getmailcore/_retrieverbases.py:1568: DeprecationWarning: invalid escape sequence \(
b' X-GM-LABELS \((?P<LABELS>.*)\) UID',
```
> use raw bytes for regexes

- docs/CHANGELOG
- docs/configuration.html
- docs/configuration.txt
- docs/getmailrc-examples
- getmail
Allow an unset XDG_CONFIG_HOME environment variable.
Simplify the documentation around the location of the configuration
directory.
> Comply more closely with the XDG basedir specification

- getmail
- getmailcore/_retrieverbases.py
This adds close() function calls for the file descriptors of the configuration file and the oldmail file once they are no longer needed.
Leaving stale unclosed file descriptors causes a python warning if one runs e.g. with PYTHONWARNINGS=d.
Fixes #53
> Fix unclosed files

- getmail
one possible simple solution for #57 
adds retriever info to log output when getmail is in idle mode
> add retriever info to idle summary log

- getmail
- getmailcore/_retrieverbases.py
Attempt to fix #62
This is WIP and I'm still waiting some exceptions to occur with my setup.  `BrokenPipeError` after IDLE was handled successfully.  I have not encountered exceptions with `retriever.close_mailbox()` yet (it was more common before). Also, the actual server response was not logged when `getmailRetrievalError` was raised before this fix, so I modified the log message.  This exception seems very rare, so I have not confirmed if the fix actually works.  
I changed the meaning of `idling` flag slightly.  With `idle = True`, `idling` becomes `True` when the session is initialized, and `False` when the session seems invalid and `retriever.go_idle()` should be skipped.
It is only tested with SimpleIMAPSSLRetriever + xoauth2 on Exchange Online.  Could you please test if it doesn't …
> Trap exceptions caused by xoauth2 token expiration 

- getmailcore/baseclasses.py
Another approach for #64 
Before #52 `getmail6` waits forever for a child to finish, so I think it is better to wait much longer, and raise an exception when timeout.  I'm not sure if 60secs is enough though.  Also I wonder how I should handle the remained child process...
> Wait much longer, and raise an exception when timeout

- docs/configuration.html
- docs/configuration.txt
- getmailcore/destinations.py
LMTP is [preferred over an LDA][1] to deliver mail to Dovecot mailboxes. Additionally, LMTP functionality has been asked for in various placed across the web, and so far users who required it had to use `fetchmail` or other projects.
*Note*: This code is affected by [bpo-42756][2] and will currently not work on an unpatched Python 3.9+ installation.
I've had this code running for a few weeks now and haven't noticed any issues — however, this getmail instance doesn't really see much traffic. If you spot anything, or want anything done differently, please feel free to comment!
[1]: <https://wiki.dovecot.org/LDA> "LDA - Dovecot Wiki"
[2]: <https://bugs.python.org/issue42756> "smtplib.LMTP.connect() raises TypeError if `timeout` is not specified"
> Implement a destination that delivers to a local LMTP server

- getmailcore/utilities.py
This allows setting a cipher list with a non-default seclevel, like:
`ssl_ciphers = DEFAULT@SECLEVEL=1`
Tested to work when connecting to a server to which the connection would
otherwise fail with:
`socket error ([SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1123))`
> allow "=" in ssl_ciphers

- docs/CHANGELOG
These were modified with the bulk copyright year change in the commit dc7a9f8.
> Revert replaced strings (from "2020" to "2021") in docs/CHANGELOG

- docs/configuration.html
- docs/configuration.txt
- docs/getmailrc-examples
- getmail-gmail-xoauth-tokens
Show how to use getmail to retrieve mail from Microsoft Office 365
when using xoauth2 authentication.
Provide steps for obtaining required user parameters (client_id,
tenant_id, etc). Also provide example getmail configuration showing
how to use them.
Works with the existing "getmail-gmail-xoauth-tokens" script.
> Microsoft Office 365/xoauth2

- getmail_maildir
On Debian 11 I ran into this 
```
Delivery error (command getmail_maildir 271452 error (1, Traceback (most recent call last):
File "/usr/bin/getmail_maildir", line 82, in <module>
main()
File "/usr/bin/getmail_maildir", line 62, in main
msg = Message(fromfile=sys.stdin)
File "/usr/lib/python3/dist-packages/getmailcore/message.py", line 124, in __init__
self.__msg = parser.parse(fromfile)
File "/usr/lib/python3.9/email/parser.py", line 109, in parse
return self.parser.parse(fp, headersonly)
File "/usr/lib/python3.9/email/parser.py", line 53, in parse
data = fp.read(8192)
TypeError: underlying read() should have returned a bytes-like object, not 'str'))
```
I assume getmail_mbox has the same problem, but since I don't have mboxes to test I cannot confirm. This PR fixes this bug but afaik …
> bugfix for python3 using bytes buffer instead of str

- getmailcore/utilities.py
I noticed that with python warnings enabled getmail would complain about an unclosed file /dev/urandom.
The reason is some code in utilities.py generating a random token. This code almost never works in the way it's written, as it is trying to read in ascii mode from /dev/urandom. However the generic exception handler makes this error to be silent.
In any case: The functionality this code tries to achieve - generating a random hex token - can easily be achieved with functionality from the python standard library. The attached patch will replace the token generation with a call to secrets.token_hex(), which does exactly what's needed here.
> Fix random token generation

- docs/configuration.html
- docs/configuration.txt
- getmailcore/destinations.py
- test/docker-compose.yml
- test/docker-mailserver-getmail6test/Dockerfile
- test/docker-mailserver-getmail6test/entrypoint.sh
- test/prepare_test.sh
- test/self_sign.sh
- test/test_getmail_with_docker_mailserver.bats
My [use case](https://github.com/spezifisch/docker-dovecot-getmail) is that I want to run multiple instances of getmail6 to fetch emails using IMAP with IDLE.
The fetched emails are delivered to the same user on the dovecot server using LMTP.
Out of the box this doesn't work because `MDA_lmtp` uses the recipient address inside the email, which contains the address of the remote account. The dovecot server doesn't (and shouldn't) know about those addresses, so I think we need a way to override the recipient address to a custom value.
For example:
```ini
[destination]
type = MDA_lmtp
host = dovecot
override = some_user
```
With this PR the email would be sent to the recipient `some_user` on the dovecot server instead of whatever the email headers say.
If you think this feature could be …
> add config parameter to MDA_lmtp to override recipient address (WIP)

- getmailcore/destinations.py
This is *not* related to #105 but could also lead to problems when:
* the connection drops at the first delivery try
* the mail is refused by the server at the second try
> fix ignored return value when retrying after SMTPServerDisconnected exception

- getmail-gmail-xoauth-tokens
Add access_type and prompt configs to the code request URL. Necessary to ensure we get a request token with all working Google OAuth2 client types (not just desktop app type),
> Add support for local webserver to receive oauth2 redirect.

- getmail-gmail-xoauth-tokens
aka (device without a browser)
I am using this on a headless server and SSH port forwarding is not an option.
> added ability to process token creation on a headless server

- getmails
getmails stops with the message "Error: dirname is not a file", if there is a directory in getmailrcdir. 
With this diff, it ignores the directories and the other files in getmailrcdir are processed.
> Ignore directories in getmailrcdir

- getmail-gmail-xoauth-tokens
Herewith I would like to propose a small extension. For certain scenarios within XOAUTH authentication with MS365 tenants it is necessary to change the URL for retrieving the verification code. Specifically, it is about the "prompt" URL parameter. So far, this parameter is set to "consent". This leads to situations where the user on whose behalf the authentication is to be performed does not have admin permissions, resulting in this user getting a prompt to log in as an administrator, even if the rights have already been granted at the enterprise level. In these cases, setting "prompt" to "login", for example, is useful. This pull request proposes to make the value of "prompt" configurable via the json file, assuming the previous fixed value of "consent" in the absence of the value in the …
> Enable overriding the prompt parameter in the XOAUTH URL

- .github/workflows/lint.yml
- docs/CHANGELOG
- docs/configuration.html
- docs/configuration.txt
- docs/faq.html
- docs/faq.txt
- docs/getmailrc-examples
- docs/troubleshooting.html
- docs/troubleshooting.txt
- getmailcore/_retrieverbases.py
- getmailcore/baseclasses.py
- getmailcore/destinations.py
- getmailcore/imap_utf7.py
- getmailcore/logging.py
- pyproject.toml
- setup.py
Test results: https://github.com/cclauss/getmail6/actions
[Ruff](https://beta.ruff.rs/) supports [over 500 lint rules](https://beta.ruff.rs/docs/rules) and can be used to replace [Flake8](https://pypi.org/project/flake8/) (plus dozens of plugins), [isort](https://pypi.org/project/isort/), [pydocstyle](https://pypi.org/project/pydocstyle/), [yesqa](https://github.com/asottile/yesqa), [eradicate](https://pypi.org/project/eradicate/), [pyupgrade](https://pypi.org/project/pyupgrade/), and [autoflake](https://pypi.org/project/autoflake/), all while executing (in Rust) tens or hundreds of times faster than any individual tool.
The ruff Action uses minimal steps to run in ~5 seconds, rapidly providing intuitive GitHub Annotations to contributors.
> Add GitHub Action to spellcheck and lint Python code

- getmailcore/_retrieverbases.py
A small fix when using GMail, that remove message label (GM-LABELS) when deleting to allow real deletion of a message. If not GMail keep the message in "All Messages".
> fix GMail deletion : remove "Labels" before deleting

- getmail-gmail-xoauth-tokens
Commit 97f0d54 ("Add local server to capture OAuth2 redirect.") improves user experience. However, it seems our Office365 instance need a specific value for redirect_uri. Typically, this configuration was used to work:
{
...
"redirect_uri": "https://login.microsoftonline.com/common/oauth2/nativeclient"
}
and now Office server returns:
AADSTS50011: The redirect URI 'http://localhost:8083/' specified in
the request does not match the redirect URIs configured for the
application 'xxxxxxxxxxx'. Make sure the redirect URI sent in the
request matches one added to your application in the Azure portal.
Navigate to https://aka.ms/redirectUriMismatchError to learn more
about how to fix this.
Close #178
> Allow to customize 'redirect_uri'

- getmail
- getmailcore/_retrieverbases.py
- getmailcore/retrievers.py
Hi,
After seeing your comment, I've made another version to implement IMAP ID extension (RFC 2971).
This version is monkey-patched the imaplib from cpython, to add ID capability and id() method.
It's disabled by default, and can use `imap_id_extension = true` in retriever section of config file to enable for specified account, or use `-I` or `--imap-id` command line option to enable for all.
BTW: it's interesting, my account for testing is no need issue ID command any more without receive , but other accounts of the same SP still need, I cannot figure out what's the logic.
> feat: IMAP ID extension (RFC 2971) support

- getmail
help message of command line is:
```
-A ACCOUNT, --account=ACCOUNT
check specified account only (may be given multiple
times)
```
example:
```
getmail -A someone@domain.com -A another@niamod.com
```
This is more useful when focusing on one mailbox in particular, and can be configure as a mutt hot key easily, such as:
```
folder-hook .... 'macro index g "!getmails -n -A someone@domain.com\n" "call getmail to get email from current account"'
```
> feat: add command line argument to support get mail for specify account(s)

- docs/configuration.html
- docs/configuration.txt
- getmail
- getmailcore/_retrieverbases.py
I add an option (`mark_read`) to mailbox settings and command line option (`-R`) to override it.
Currently, it's only has the effect on imap accounts, since POP3 is quite simple and it mostly mark read automatically (I have not tried on POP3 account, so I leave it with just 'pass'). 
the command option is `-R` as below:
```text
Overrides:
....
-R, --mark-read     mark read after retrieve
```
and the option in config file is `mark_read = true|false` (default is false as before) as below:
```
[options]
mark_read = true
```
> feat: mark read after retrieved

- getmail
I think I found the correct way to make `mark_read` option act as `-ds,` command line argument. just need add UNSEEN flag to search.
One of the functions of configuration files is to reduce the number of parameters you have to type on the command line, right?
BTW: I cannot reopen #194 because I've force pushed my master branch, and github does not allow to reopen.
> fix: make mark_read option act same as -ds,

- docs/configuration.html
- docs/configuration.txt
- getmailcore/_retrieverbases.py
- getmailcore/retrievers.py
Adds support for use_xoauth2 configuration and OAuth2 support to POP3 retrievers.
* getmailcore/_retrieverbases.py (POP3RetrieverBase.initialize): Handle use_xoauth2.
* getmailcore/retrievers.py (SimplePOP3Retriever, SimplePOP3SSLRetriever), (BrokenUIDLPOP3Retriever, BrokenUIDLPOP3SSLRetriever), (MultidropPOP3Retriever, MultidropPOP3SSLRetriever), (MultidropSDPSRetriever): New ConfBool `use_xoauth2'.
* docs/configuration.html, docs/configuration.txt: Document it.
> pop3: Support use_xoauth2.

- docs/getmailrc-examples
Azure Active Directory is now called Microsoft Entra ID.
Do not include redirect_uri. See https://github.com/getmail6/getmail6/issues/203#issuecomment-2272436981
> Update getmailrc-example #13

- docs/getmailrc-examples
I removed port number 8083 from example 13. On August 12, 2024, I tested on Azure and confirmed that it was not necessary to have port number 8083 on the URL for redirection_uri when creating an Azure app. See also the suggestion from @ykasap https://github.com/getmail6/getmail6/pull/204#issuecomment-2274880089.
> Remove port number 8083 from example No. 13 in getmailrc-example

- docs/getmailrc-examples
Fix permission scope strings
Remove unnecessary permissions (POP and SMTP)
Add example 14 for Personal Microsoft accounts
See also: #203 and #204
> fix #203: Update getmailrc-examples #13 and add #14

- Makefile
- getmailcore/__init__.py
pyp2spec is a tool for generating Fedora packages from pypi.
When running it for getmail6 I got some errors:
* License is an invalid SPDX expression
* sdist isn't uploaded to pypi
This PR contains the fixes for these errors, I hope you can merge these changes and do a release.
> Pyp2 fixes

- docs/configuration.html
- docs/configuration.txt
- getmail
- getmailcore/_retrieverbases.py
Patch to close bug #219.
New configuration parameter imap_cache_uid.
When set (to a relative or absolute filename), it will cache the highest UID seen so that old UIDs are not fetched over and over again.
> Increase imap efficiency through UID cache #219

- .github/workflows/publish.yml
- .github/workflows/publish6.yml
This workflow automatically build and publish getmail to PyPI and does digital attestation when a tag gets created.
I also included a step to check of the tag matches the version in getmailcore (I always forget to update that version).
For this to work you must allow/configure this github repository to publish on pypi.org (you can easily do this by logging into pypi.org, navigate to the getmail projects and open the "publishing" setting).
The advantage of this is that you don't have to mess with tokens and the digital attestation proves that the build was done using this workflow (and wasn't tampered with).
> Publish to pypi workflow

- setup.py
I don't know why the documentation directory includes the version number, this seems to be uncommon (on Linux).
> Don't use version for documentation directory

- PKG-INFO
- README
- setup.py
It seems like `getmail-gmail-xoauth-tokens` isn't GPL-2.0 licensed, add Apache Software License to PKG-INFO, setup.py and add some notes to the README.
> Add Apache-2.0 license

- docs/COPYING
- getmail_maildir
- getmail_mbox
If you may wonder why I'm creating these pull requests, I'm trying to get getmail packaged in Fedora.
I received another review-comment to fix the FSF address in the headers.
The GPL-2 license in getmail has been modified to be GPL-2 only, I only updated the address and the example signature in COPYING (copied the latest version as-is).
> Fix incorrect FSF address in COPYING and headers

- Makefile
- pyproject.toml
- test/test_mock_servers.py
Hi! How do you like these tests?
These tests were made to run without any changes in getmail6.
I also tried to cover as much as possible in the different configurations.
I used `pytest-cov` to validate the coverage, it seems to work fine except for the fork-ing code. I think this should be rewritten to processing (that will make getmail6 also compatible with platforms that don't support `fork`).
There are still some functionatlity I'd like to add tests for (like Gmail labels, idle mode, SDPS (is anyone using this?))
It might also be useful to add some assertions to check if the "received" mails are actually stored.
I also omitted the SSL code for now, not sure how easy this would be to implement (with self signed certificates?)
> Mock server tests

- test/test_mock_servers.py
Thanks for releasing 6.19.9!
I noticed some of the forking has changed to multiprocessing, which is a great improvement!
I hope all forking can be removed at some point, do you need some help with that?
It only seems like that nested multiprocessing (using spawn) isn't supported, this PR fixes the mock server tests by switching to fork (for the tests).
> use multiprocessing start method for for tests
